### PR TITLE
Run the given highway even without drive

### PR DESCRIPTION
**Pull request by BenchR267**
There is still the problem, that console is printing the help description if it doesn't find the command in the group (https://github.com/vapor/console/blob/master/Sources/Console/Console/Console%2BRun.swift#L40-L44).

### CODE REVIEW

**Comment by kdawgwilk** [comment]
I almost had this working with the fallback command on Console Group here: https://github.com/vapor/console/blob/master/Sources/Console/Console/Console%2BRun.swift#L31 but we might need to open a PR to console to fix it to work as we expect.  The way it seems they intended for it to work was if no command was given at all it would fallback to the given command the problem for us though is we need to pass that fallback command arguments

**Comment by BenchR267** [comment]
Yeah, that probably needs to be fixed in Console. Let's just fix it there first and merge this pull request afterwards.

**Comment by kdawgwilk** [comment]
Opened and issue over on the console repo: vapor/console#42

**Comment by BenchR267** [comment]
I move this branch to the original repository instead of the fork and re-open the pull request :)

**Pull request closed without merging**
